# Benchmarks that have not been vetted for builds, runs, noisiness, run length, etc.

[[Benchmarks]]
  Name = "uber_zap"
  # Repo = "github.com/uber-go/zap/benchmarks"
  Repo = "go.uber.org/zap/benchmarks"
  Benchmarks = "Benchmark"
  Disabled = true # Not building today

[[Benchmarks]]
  Name = "bindata"
  Repo = "github.com/kevinburke/go-bindata"
  Benchmarks = "Benchmark"

# A noise-checking recent run (used to move some tests into benchmarks-50.toml)

# name                                            old time/op  new time/op  delta
# FromBytes-12                                    8.03ns ± 3%  7.64ns ± 6%   -4.86%  (p=0.000 n=23+20)
# FromString-12                                    266ns ±11%   263ns ± 8%     ~     (p=0.213 n=21+21)
# FromStringUrn-12                                 268ns ± 8%   262ns ± 9%     ~     (p=0.109 n=21+25)
# FromStringWithBrackets-12                        270ns ± 7%   263ns ± 9%   -2.57%  (p=0.034 n=22+25)
# NewV1-12                                         123ns ± 3%   119ns ± 3%   -2.73%  (p=0.000 n=21+22)
# NewV2-12                                         118ns ± 9%   118ns ± 5%     ~     (p=0.295 n=25+23)
# NewV3-12                                         629ns ±14%   658ns ± 7%   +4.63%  (p=0.004 n=23+23)
# NewV4-12                                         868ns ± 8%   841ns ±12%     ~     (p=0.078 n=25+25)
# NewV5-12                                         753ns ± 8%   675ns ±10%  -10.35%  (p=0.000 n=23+24)
# MarshalBinary-12                                1.14ns ± 4%  0.40ns ± 8%  -64.72%  (p=0.000 n=22+25)
# MarshalText-12                                   203ns ±16%   198ns ±24%     ~     (p=0.418 n=24+25)
# UnmarshalBinary-12                              5.03ns ± 3%  5.10ns ± 3%   +1.44%  (p=0.000 n=23+23)
# UnmarshalText-12                                81.0ns ± 3%  85.4ns ± 2%   +5.40%  (p=0.000 n=21+22)
# MarshalToString-12                               147ns ±10%   140ns ±11%   -4.82%  (p=0.005 n=23+24)
# TarjanSCCGnp_10_tenth-12                        8.90µs ± 8%  8.44µs ± 5%   -5.18%  (p=0.000 n=23+23)
# TarjanSCCGnp_100_tenth-12                        273µs ± 8%   262µs ± 6%   -3.89%  (p=0.000 n=23+25)
# TarjanSCCGnp_1000_tenth-12                      19.7ms ± 9%  19.3ms ± 8%     ~     (p=0.092 n=25+25)
# TarjanSCCGnp_10_half-12                         15.6µs ± 8%  14.8µs ± 5%   -4.96%  (p=0.000 n=24+25)
# TarjanSCCGnp_100_half-12                        1.06ms ± 7%  1.03ms ± 9%   -2.54%  (p=0.017 n=24+24)
# TarjanSCCGnp_1000_half-12                       87.7ms ± 4%  85.3ms ± 7%   -2.73%  (p=0.000 n=22+23)
# AStarGnp_10_tenth-12                            2.31µs ± 9%  2.08µs ± 9%   -9.90%  (p=0.000 n=25+25)
# AStarGnp_100_tenth-12                            259µs ± 6%   252µs ± 9%   -2.68%  (p=0.006 n=24+25)
# AStarGnp_1000_tenth-12                          11.7ms ±14%  11.5ms ±10%     ~     (p=0.407 n=25+25)
# AStarGnp_10_half-12                             8.31µs ± 9%  7.91µs ±13%   -4.78%  (p=0.000 n=25+25)
# AStarGnp_100_half-12                             320µs ±16%   320µs ± 9%     ~     (p=0.830 n=24+24)
# AStarGnp_1000_half-12                           24.8ms ±16%  24.4ms ±18%     ~     (p=0.551 n=25+25)
# AStarUndirectedmallWorld_10_2_2_2-12            30.8µs ± 6%  28.7µs ± 7%   -6.70%  (p=0.000 n=24+24)
# AStarUndirectedmallWorld_10_2_2_2_Heur-12       15.9µs ± 7%  15.2µs ± 8%   -4.48%  (p=0.000 n=24+24)
# AStarUndirectedmallWorld_10_2_5_2-12            61.6µs ±22%  57.1µs ±21%   -7.33%  (p=0.004 n=25+22)
# AStarUndirectedmallWorld_10_2_5_2_Heur-12       21.5µs ±10%  20.1µs ±10%   -6.70%  (p=0.000 n=25+24)
# AStarUndirectedmallWorld_100_5_10_2-12          1.65ms ±13%  1.61ms ±14%     ~     (p=0.058 n=24+25)
# AStarUndirectedmallWorld_100_5_10_2_Heur-12     1.26ms ±10%  1.20ms ± 6%   -5.27%  (p=0.000 n=24+24)
# AStarUndirectedmallWorld_100_5_20_2-12          2.24ms ±11%  2.08ms ±10%   -7.14%  (p=0.000 n=25+24)
# AStarUndirectedmallWorld_100_5_20_2_Heur-12     1.27ms ±10%  1.21ms ±10%   -4.46%  (p=0.001 n=22+23)
# Dominators/nested_if_n1024-12                   3.22ms ±10%  2.93ms ±13%   -8.86%  (p=0.000 n=25+25)
# Dominators/nested_if_n128-12                     390µs ± 7%   351µs ± 8%   -9.90%  (p=0.000 n=24+25)
# Dominators/nested_if_n16-12                     47.1µs ± 5%  43.1µs ± 5%   -8.42%  (p=0.000 n=25+25)
# Dominators/nested_if_n2048-12                   6.60ms ± 9%  5.93ms ±11%  -10.21%  (p=0.000 n=25+25)
# Dominators/nested_if_n256-12                     792µs ± 9%   708µs ± 6%  -10.69%  (p=0.000 n=24+23)
# Dominators/nested_if_n32-12                     96.9µs ± 6%  86.2µs ± 7%  -11.01%  (p=0.000 n=24+25)
# Dominators/nested_if_n512-12                    1.58ms ± 9%  1.44ms ± 9%   -9.08%  (p=0.000 n=25+25)
# Dominators/nested_if_n64-12                      192µs ± 8%   172µs ± 8%  -10.71%  (p=0.000 n=25+25)
# RandomGraphDominators/gnm-n=1e3-m=1e3-12        1.64ms ±10%  1.50ms ± 6%   -8.55%  (p=0.000 n=25+25)
# RandomGraphDominators/gnm-n=1e3-m=3e3-12        1.93ms ±12%  1.72ms ± 8%  -10.75%  (p=0.000 n=25+24)
# RandomGraphDominators/gnm-n=1e3-m=1e4-12        3.10ms ± 9%  2.90ms ± 9%   -6.28%  (p=0.000 n=25+25)
# RandomGraphDominators/gnm-n=1e3-m=3e4-12        5.98ms ±11%  5.77ms ± 6%   -3.44%  (p=0.005 n=25+25)
# RandomGraphDominators/gnm-n=1e4-m=1e4-12        17.3ms ±13%  15.6ms ± 5%   -9.83%  (p=0.000 n=24+24)
# RandomGraphDominators/gnm-n=1e4-m=3e4-12        22.2ms ± 8%  21.1ms ±10%   -4.89%  (p=0.000 n=24+25)
# RandomGraphDominators/gnm-n=1e4-m=1e5-12        39.3ms ±11%  37.8ms ± 7%   -3.82%  (p=0.000 n=24+25)
# RandomGraphDominators/gnm-n=1e4-m=3e5-12        81.4ms ±12%  77.8ms ± 6%   -4.35%  (p=0.000 n=25+23)
# RandomGraphDominators/gnm-n=1e5-m=1e5-12         225ms ± 6%   215ms ± 5%   -4.63%  (p=0.000 n=19+23)
# RandomGraphDominators/gnm-n=1e5-m=3e5-12         311ms ± 5%   303ms ± 5%   -2.79%  (p=0.000 n=23+19)
# RandomGraphDominators/gnm-n=1e5-m=1e6-12         584ms ± 3%   572ms ±11%     ~     (p=0.120 n=23+23)
# RandomGraphDominators/gnm-n=1e5-m=3e6-12         1.29s ±10%   1.27s ± 5%   -1.85%  (p=0.022 n=25+18)
# RandomGraphDominators/gnm-n=1e6-m=1e6-12         2.50s ± 4%   2.41s ± 5%   -3.35%  (p=0.000 n=24+25)
# RandomGraphDominators/gnm-n=1e6-m=3e6-12         4.13s ± 3%   4.01s ± 4%   -2.75%  (p=0.000 n=24+25)
# RandomGraphDominators/gnm-n=1e6-m=1e7-12         9.06s ± 2%   8.94s ± 1%   -1.30%  (p=0.000 n=25+24)
# RandomGraphDominators/gnm-n=1e6-m=3e7-12         22.1s ± 1%   21.9s ± 1%   -1.15%  (p=0.000 n=22+23)
# RandomGraphDominators/dup-n=1e3-d=0.8-a=0.1-12  1.79ms ± 9%  1.60ms ± 7%  -10.54%  (p=0.000 n=24+25)
# RandomGraphDominators/dup-n=1e3-d=0.5-a=0.2-12  5.11ms ± 6%  4.88ms ± 8%   -4.34%  (p=0.000 n=20+23)
# RandomGraphDominators/dup-n=1e4-d=0.8-a=0.1-12  19.4ms ±12%  17.6ms ± 5%   -9.52%  (p=0.000 n=25+22)
# RandomGraphDominators/dup-n=1e4-d=0.5-a=0.2-12   140ms ± 7%   136ms ± 4%   -3.26%  (p=0.000 n=25+23)
# RandomGraphDominators/dup-n=1e5-d=0.8-a=0.1-12   237ms ± 5%   222ms ± 9%   -6.38%  (p=0.000 n=21+25)
# RandomGraphDominators/dup-n=1e5-d=0.5-a=0.2-12   6.39s ± 5%   6.30s ± 4%   -1.44%  (p=0.008 n=24+22)
# LouvainDirectedMultiplex-12                     43.0ms ±10%  38.6ms ±33%  -10.13%  (p=0.000 n=25+23)
# LouvainDirected-12                              38.1ms ± 8%  35.3ms ± 9%   -7.45%  (p=0.000 n=25+22)
# LouvainMultiplex-12                             32.9ms ±13%  29.7ms ±15%   -9.73%  (p=0.000 n=24+24)
# Louvain-12                                      28.9ms ± 7%  26.3ms ±12%   -9.07%  (p=0.000 n=23+23)
# WalkAllBreadthFirstGnp_10_tenth-12              3.88µs ± 7%  3.43µs ± 8%  -11.67%  (p=0.000 n=24+25)
# WalkAllBreadthFirstGnp_100_tenth-12              158µs ± 9%   151µs ± 7%   -4.80%  (p=0.000 n=24+24)
# WalkAllBreadthFirstGnp_1000_tenth-12            12.3ms ± 9%  12.4ms ± 8%     ~     (p=0.532 n=25+24)
# WalkAllBreadthFirstGnp_10_half-12               8.33µs ± 7%  7.94µs ± 8%   -4.71%  (p=0.000 n=24+25)
# WalkAllBreadthFirstGnp_100_half-12               609µs ± 7%   597µs ±12%     ~     (p=0.189 n=25+25)
# WalkAllBreadthFirstGnp_1000_half-12             58.6ms ± 7%  57.2ms ±10%     ~     (p=0.081 n=25+25)
# WalkAllDepthFirstGnp_10_tenth-12                3.76µs ±10%  3.37µs ± 8%  -10.21%  (p=0.000 n=25+23)
# WalkAllDepthFirstGnp_100_tenth-12                158µs ± 9%   149µs ± 9%   -5.52%  (p=0.000 n=25+25)
# WalkAllDepthFirstGnp_1000_tenth-12              12.4ms ± 7%  12.1ms ± 4%     ~     (p=0.054 n=23+22)
# WalkAllDepthFirstGnp_10_half-12                 8.41µs ± 6%  7.84µs ± 8%   -6.77%  (p=0.000 n=24+25)
# WalkAllDepthFirstGnp_100_half-12                 603µs ±14%   588µs ±12%     ~     (p=0.136 n=25+25)
# WalkAllDepthFirstGnp_1000_half-12               57.8ms ± 7%  57.2ms ±11%     ~     (p=0.476 n=25+25)
# [Geo mean]                                       523µs        491µs        -6.11%
