[[Configurations]]
  Name = "Resched"
  GcFlags = "-d=ssa/preempt_loops/on"
  RunEnv = ["GOGC=100"]
  RunFlags = ["-test.short"]
  RunWrapper = ["foo"]
  Root = "$HOME/work/go-debug"
  Disabled = true

[[Configurations]]
  Name = "NoResched"
  GcFlags = "-d=ssa/insert_resched_checks/off"
  RunEnv = ["GOGC=100"]
  RunFlags = ["-test.short"]
  Root = "$HOME/work/go/"
